### PR TITLE
Make {Array,Vector}.Mutable.Linear lazier

### LINKED ISSUE #142: Data.Array.Mutable.Linear.Array is unnecessarily strict
**Describe the bug**

As a result of #135, `Data.Array.Mutable.Linear.Array` is stricter than necessary; `read`'s force the elements to WHNF. This is counter-intutitive since most other Haskell collections are lazy on the values.

**To Reproduce**

```haskell
{-# LANGUAGE LinearTypes #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}

module Main where

import Data.Function ((&))
import qualified Prelude.Linear as L
import qualified Data.Array.Mutable.Linear as Array
import Prelude.Linear (Unrestricted(..))

processArr :: Array.Array () #-> Unrestricted ()
processArr arr =
  Array.write arr 0 (error "this should not be evaluated") L.& \arr ->
  Array.read arr 0 L.& \(arr, Unrestricted _) ->
    arr `L.lseq` Unrestricted ()

main :: IO ()
main =
   Array.fromList [()] processArr
     & \(Unrestricted a) -> print a
```

**Expected behavior**

We expect the above program to print `()`, however it currently fails.

We should also have a test case for this.

### PR DESCRIPTION
**Pull request by utdemir**
Closes #142.

This PR changes wraps the result of `Unsafe.MutableArray.read` with an
unboxed tuple, so the array lookup can be evaluated without evaluating
the result.

Because of that, now `Data.{Array,Vector}.Mutable.Linear.read` functions
does not unnecessarily force the return value.

I added a test case about strictness issue just for `Array`'s. Because
Vector's `read` function returns the result linearly as opposed to
`Array` which wraps it with an `Unrestricted`. I think this is another
error, so I'll fix that with a separate PR:

```
read :: HasCallStack => Vector a #-> Int -> (Vector a, a)
read :: HasCallStack => Array a #-> Int -> (Array a, Unrestricted a)
```

---

While implementing this, I also noticed that the issue fixed in #135 also applies
to vectors, so this PR also fixes that while adding a test case.

### CODE REVIEW

File: src/Data/Array/Mutable/Linear.hs [hunk 1]
```diff
@@ -120,14 +120,15 @@ read = Unsafe.toLinear readUnsafe
     readUnsafe :: Array a -> Int -> (Array a, Unrestricted a)
     readUnsafe arr@(Array size mutArr) ix
       | indexInRange size ix =
-          let !val = Unsafe.readMutArr mutArr ix
-          in  (arr, Unrestricted val)
+          let !(# a #) = Unsafe.readMutArr mutArr ix
```
Comment (utdemir) [inline src/Data/Array/Mutable/Linear.hs:123]: I do not completely understand why we still need the bang pattern here, I thought pattern matching on the result would evaluate it even without the bang pattern. Without it, the read/write reordering issue reappears.

Comment (aspiwack) [reply src/Data/Array/Mutable/Linear.hs:123]: That's actually fairly surprising to me too. It does sound wrong. A `let` at an unboxed value should always be evaluated. I could understand if `let (# a #) = …` was illegal syntax, I suppose (we can make a case that there shouldn't be a lazy pattern-matching on unboxed tuple). But I wouldn't have expected it to fail to evaluate its right hand side.

I did find the explanation, though, it's in the last paragraph of the [relevant manual section](https://downloads.haskell.org/ghc/latest/docs/html/users_guide/glasgow_exts.html#extension-UnboxedTuples). Note how the desugaring breaks the strictness assumption by adding an extra thunk around the computation.

It may be best to avoid `let (#…` and replace them with explicit `case` to avoid surprises. But `let !p = …` is, of course, equivalent to a `case`.

File: src/Data/Array/Mutable/Linear.hs [hunk 2]
```diff
@@ -120,14 +120,15 @@ read = Unsafe.toLinear readUnsafe
...
+          in  (arr, Unrestricted a)
       | otherwise = error "Read index out of bounds."
 
 -- | Using first element as seed, resize to a constant array
 resize :: HasCallStack => Int -> Array a #-> Array a
 resize newSize (Array _ mutArr) =
-  Array newSize (Unsafe.newMutArr newSize (Unsafe.readMutArr mutArr 0))
+  let (# a #) = Unsafe.readMutArr mutArr 0
```
Comment (aspiwack) [inline src/Data/Array/Mutable/Linear.hs:130]: So we need
```suggestion
  let !(# a #) = Unsafe.readMutArr mutArr 0
```

File: src/Unsafe/MutableArray.hs [hunk 3]
```diff
@@ -69,7 +73,8 @@ readMutArr mutArr (I# ix) =
 -- fails for a size smaller than the size of the given array.
 resizeMutArr :: MutArr# a -> Int -> MutArr# a
 resizeMutArr mutArr newSize =
-  resizeMutArrSeed mutArr (readMutArr mutArr 0) newSize
+  let (# a #) = readMutArr mutArr 0
```
Comment (aspiwack) [inline src/Unsafe/MutableArray.hs:76]: And
```suggestion
  let !(# a #) = readMutArr mutArr 0
```

**Review by aspiwack — APPROVED** [review]

File: src/Data/Array/Mutable/Linear.hs (hunk 1 above)
Comment (utdemir) [reply src/Data/Array/Mutable/Linear.hs:123]: To be honest, after I replaced the case with a `let` initially, I think the let binding looks clearer. However, I'm happy to replace it with an explicit `case` if that's what you prefer.

Comment (aspiwack) [reply src/Data/Array/Mutable/Linear.hs:123]: It doesn't matter for today. Let's see how often we get owned by this, before deciding for a solution.
